import{a as g,S as L,i as u}from"./assets/vendor-56bcefdc.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(r){if(r.ep)return;r.ep=!0;const t=o(r);fetch(r.href,t)}})();const b="44071791-e24b31a34b7a75e1ae02e9c2e",w="https://pixabay.com/api/";async function f(e,s=1){const o=await g.get(`${w}`,{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}});if(o.status!==200)throw new Error("Failed to fetch images");return o.data}let c;function h(e,s){const o=document.querySelector(".gallery"),i=o.clientHeight;s&&(o.innerHTML=""),o.innerHTML+=e.map(t=>`
    <a href="${t.largeImageURL}" class="gallery-item">
      <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy">
      <div class="info">
        <p><b>Likes:</b> ${t.likes}</p>
        <p><b>Views:</b> ${t.views}</p>
        <p><b>Comments:</b> ${t.comments}</p>
        <p><b>Downloads:</b> ${t.downloads}</p>
      </div>
    </a>`).join(""),c?c.refresh():c=new L(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250});const r=o.clientHeight;window.scrollBy({top:r-i,behavior:"smooth"})}function n(e){u.error({title:"Error",message:e,position:"topRight"})}function v(){const e=document.querySelector(".gallery");e.innerHTML=""}function y(){console.log("+"),document.querySelector(".div-loader").classList.remove("hidden")}function m(){console.log("-"),setTimeout(()=>{document.querySelector(".div-loader").classList.add("hidden")},2e3)}function d(e){const s=document.querySelector(".load-more");e?s.classList.remove("hidden"):s.classList.add("hidden")}let a=1,p="";document.querySelector("#search-form").addEventListener("submit",async e=>{e.preventDefault();const s=e.target.elements.searchQuery.value.trim();if(!s){n("Please enter a search query");return}p=s,a=1,v(),d(!1),y();try{const o=await f(s);o.hits.length===0?n("Sorry, there are no images matching your search query. Please try again!"):(h(o.hits,!0),d(o.totalHits>a*15))}catch(o){n(o.message)}finally{m()}});document.querySelector(".load-more").addEventListener("click",async()=>{a+=1,y();try{const e=await f(p,a);h(e.hits,!1),d(e.totalHits>a*15),e.totalHits<=a*15&&u.info({title:"info",message:"Weare sorry, but you`ve reached the end of search result.",position:"topRight"})}catch(e){n(e.message)}finally{m()}});
//# sourceMappingURL=commonHelpers.js.map
